apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "argo-demo"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deliver"
            - name: "git-promotion"
              properties:
                repository: "https://github.com/jkleinlercher/keptn-argo-dev"
                secretname: "keptncademo"
                strategy: "branches"            
#            - name: "test"
#            - name: "evaluate"
#            - name: "promote"
    - name: "hardening"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "kickoff"
            - name: "deliver"
            - name: "git-promotion"
              properties:
                repository: "https://github.com/jkleinlercher/keptn-argo-dev"
                secretname: "keptncademo"
                strategy: "branches"            
#            - name: "test"
#            - name: "evaluate"
#            - name: "promote"
    - name: "production"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "kickoff"
            - name: "deliver"
#            - name: "test"
#            - name: "evaluate"
#            - name: "promote"
