apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "argo-demo"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "kickoff"
          tasks:
            - name: approval
              properties: 
                pass: manual
                warning: manual 
        - name: "artifact-delivery"
          triggeredOn:
            - event: "dev.kickoff.finished"
          tasks:
            - name: "deliver"
            - name: "test"
            - name: "evaluation"
            - name: "promote"
    - name: "hardening"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deliver"
            - name: "test"
            - name: "evaluation"
            - name: "promote"
    - name: "production"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deliver"
            - name: "test"
            - name: "evaluation"
            - name: "promote"
