apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deliver.triggered
      requests:
        - curl --request POST https://asdf1234
      subscriptionID: f5e47ed7-ce07-45ed-a6cd-ef5afb60f5f8
      sendFinished: true
