apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.promote.triggered
      requests:
        - >-
          curl --request POST https://eook6pd5dkebdn4.m.pipedream.net
      subscriptionID: 0572a11d-8932-44f1-a419-ab631e9052af
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.check-budget.triggered
      requests:
        - >-
          curl --request POST https://eook6pd5dkebdn4.m.pipedream.net
      subscriptionID: d0ddde87-21ac-424f-9941-46f49d3b15ec
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.deliver-infra.triggered
      requests:
        - >-
          curl --request POST https://eook6pd5dkebdn4.m.pipedream.net
      subscriptionID: bf3d8838-84a1-44d8-a7e3-f5553965fdae
      sendFinished: true
      sendStarted: true
