apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deliver.triggered
      requests:
        - "curl --header 'Authorization: Bearer {{.env.secret_argokeptn_token}}'
          --request POST --data
          '{\"infos\":[{\"name\":\"triggeredid\",\"value\":\"{{.id}}\"},{\"name\
          \":\"shkeptncontext\",\"value\":\"{{.shkeptncontext}}\"}],\"prune\":t\
          rue}'
          https://argo.research.dev.dynatracelabs.com/api/v1/applications/{{.da\
          ta.labels.appname}}/sync"
      envFrom:
        - name: secret_argokeptn_token
          secretRef:
            name: argo-keptn
            key: token
      subscriptionID: f5e47ed7-ce07-45ed-a6cd-ef5afb60f5f8
      sendFinished: false
